#include "item_list.hpp"
#include "logic.hpp"
#include "rnd/item_override.h"
#include <array>
using namespace Logic;
using namespace std;
using namespace rnd;
static std::array<Item, KEY_ENUM_MAX> itemTable;

void ItemTable_Init() {    //repeatable denotes that an item in a vanilla playthrough can be obtained again after resetting time
    //Item(0, 0, "test", "test", Region::region, hint, 0, ItemCategory::Misc, LocationCategory::test, );
    //itemTable[EXAMPLE] =                        Item(advancement, repeatable,    logicVar,                         {English name     				         French          					              Spanish},                                             HintKey,               GetItemIndexValue,                  item type);
    itemTable[TEST] = Item();
    itemTable[NONE]                              = Item(false,     false,          &noVariable,                  Text{"No Item",                         "Rien",                                             "Sin Objeto" },                                        NONE,                  (u32)GetItemID::GI_NONE,                ITEMTYPE_EVENT);
    itemTable[KOKIRI_SWORD]                      = Item(true ,     false,          &KokiriSword,                 Text{"Kokiri Sword",                    "Épée Kokiri",                                      "Espada Kokiri" },                                     KOKIRI_SWORD,          (u32)GetItemID::GI_KOKIRI_SWORD,        ITEMTYPE_ITEM );
	itemTable[GREAT_FAIRYS_SWORD]                = Item(true ,     false,          &GreatFairySword,             Text{"Great Fairy's Sword",             "Grande Épée de Fees",                              "Espada de la Gran Hada"},                             GREAT_FAIRYS_SWORD,    (u32)GetItemID::GI_GREAT_FAIRY_SWORD,   ITEMTYPE_GFAIRY );
    itemTable[HEROS_SHIELD]                      = Item(false,     true,           &HerosShield,                 Text{"Heros Shield",                    "Bouclier du Heros",                                "Escudo del Heroe"},                                   HEROS_SHIELD,          (u32)GetItemID::GI_SHIELD_HERO,         ITEMTYPE_ITEM );
    itemTable[DEKU_STICK]                        = Item(true ,     true,           &DekuStick,                   Text{"Deku Stick",                      "Bâton Mojo",                                       "palos deku" },                                        DEKU_STICK,            (u32)GetItemID::GI_STICKS_1,            ITEMTYPE_ITEM );
    itemTable[LAND_TITLE]                        = Item(true,      true,           &LandTitle,                   Text{"Land Title Deed",				 "Titre de propriete fonciere",                      "Escritura de propiedad de la Tierra" },               LAND_TITLE,            (u32)GetItemID::GI_TOWN_TITLE_DEED,     ITEMTYPE_TRADE );
    itemTable[SWAMP_TITLE]                       = Item(true,      true,           &SwampTitle,                  Text{"Swamp Title Deed",				 "Titre de propriete des marais",	                 "Escriture de propiedad del pantano" },                SWAMP_TITLE,           (u32)GetItemID::GI_SWAMP_TITLE_DEED,    ITEMTYPE_TRADE );
    itemTable[MOUNTAIN_TITLE]                    = Item(true,      true,           &MountainTitle,               Text{"Mountain Title Deed",			 "Titre de propriete de la montagne",                "Escitura de propiedad de la montana" },               MOUNTAIN_TITLE,        (u32)GetItemID::GI_MOUNTAIN_TITLE_DEED, ITEMTYPE_TRADE );
    itemTable[OCEAN_TITLE]                       = Item(true,      true,           &OceanTitle,                  Text{"Ocean Title Deed",				 "Titre de propriete de l'ocean",	                 "Escitura de propiedad del oceano" },                  OCEAN_TITLE,           (u32)GetItemID::GI_OCEAN_TITLE_DEED,    ITEMTYPE_TRADE );
    itemTable[BOMBERS_NOTEBOOK]                  = Item(true,      false,          &BombersNotebook,             Text{"Bomber's Notebook",			     "Carnet de bombardier",				             "Cuaderno de bombardero" },                            BOMBERS_NOTEBOOK,      (u32)GetItemID::GI_BOMBERS_NOTEBOOK,    ITEMTYPE_ITEM);
    itemTable[ROOM_KEY]                          = Item(true,      true,           &RoomKey,                     Text{"Room Key",						 "Clef de chambre",					                 "Llave del cuarto" },                                  ROOM_KEY,              (u32)GetItemID::GI_ROOM_KEY,            ITEMTYPE_QUEST );
    itemTable[LETTER_KAFEI]                      = Item(true,      true,           &LetterKafei,                 Text{"Letter to Kafei",				 "Lettre a Kafei",					                 "Carta a Kafei" },                                     LETTER_KAFEI,          (u32)GetItemID::GI_LETTER_TO_KAFEI,     ITEMTYPE_QUEST );
    itemTable[PENDANT_MEMORIES]                  = Item(true,      true,           &PendantAccess,               Text{"Pendant of Memories",			 "Pendentif de Souvenirs",			                 "Colgante de recuerdos" },                             PENDANT_MEMORIES,      (u32)GetItemID::GI_PENDANT_OF_MEMORIES, ITEMTYPE_QUEST );
    itemTable[LETTER_MAMA]                       = Item(true,      true,           &LetterMama,                  Text{"Special Delivery to Mama",		 "Livraison speciale a maman",	               	     "Entrega especial a mama" },                           LETTER_MAMA,           (u32)GetItemID::GI_LETTER_TO_MAMA,      ITEMTYPE_QUEST );
    itemTable[MOONS_TEAR]                        = Item(true,      true,           &MoonsTear,                   Text{"Moon's Tear",					 "Larme de lune",					                 "Lagrima de luna" },                                   MOONS_TEAR,            (u32)GetItemID::GI_MOONS_TEAR,          ITEMTYPE_TRADE );
    itemTable[SPIN_ATTACK]                       = Item(true,      false,          &SpinAttack,                  Text{"Spin Attack",					 "attaque de rotation",				                 "ataque giratorio" },                                  SPIN_ATTACK,           0x2C,                                   ITEMTYPE_GFAIRY );
    itemTable[LENS_OF_TRUTH]                     = Item(true,      false,          &LensOfTruth,                 Text{"Lens of Truth",                   "Loupe de vérité",                                  "Lupa de la Verdad"},                                  LENS_OF_TRUTH,         (u32)GetItemID::GI_LENS_OF_TRUTH,       ITEMTYPE_ITEM );
    itemTable[HEROS_BOW]                         = Item(true,      false,          &HerosBow,                    Text{"Hero's Bow",                      "Hero's Bow",                                       "Hero's Bow"},                                         HEROS_BOW,             (u32)GetItemID::GI_HEROS_BOW,           ITEMTYPE_ITEM );
    itemTable[FIRE_ARROWS]                       = Item(true,      false,          &FireArrows,                  Text{"Fire Arrow",                      "Flèche de feu",                                    "Flecha de fuego"},                                    FIRE_ARROWS,           (u32)GetItemID::GI_FIRE_ARROW,          ITEMTYPE_ITEM );
    itemTable[ICE_ARROWS]                        = Item(true,      false,          &IceArrows,                   Text{"Ice Arrow",                       "Flèche de glace",                                  "Flecha de hielo"},                                    ICE_ARROWS,            (u32)GetItemID::GI_ICE_ARROW,           ITEMTYPE_ITEM );
    itemTable[LIGHT_ARROWS]                      = Item(true,      false,          &LightArrows,                 Text{"Light Arrow",                     "Flèche de lumière",                                "Flecha de luz"},                                      LIGHT_ARROWS,          (u32)GetItemID::GI_LIGHT_ARROW,         ITEMTYPE_ITEM );
    itemTable[HOOKSHOT]                          = Item(true,      false,          &Hookshot,                    Text{"Hookshot",					     "Grappin",							                 "Gancho" },								            HOOKSHOT,              (u32)GetItemID::GI_HOOKSHOT,            ITEMTYPE_ITEM );
	itemTable[MAGIC_BEAN]                        = Item(true,      true,           &MagicBean,                   Text{"Magic Bean",                      "Haricot magique",                                  "Habichuelas mágicas"},                                MAGIC_BEAN,            (u32)GetItemID::GI_MAGIC_BEAN,          ITEMTYPE_ITEM );
    itemTable[MAGIC_BEAN_PACK]                   = Item(true,      true,           &MagicBeanPack,               Text{"Magic Bean Pack",                 "Paquet de haricots magiques",                      "Lote de habichuelas mágicas"},                        MAGIC_BEAN_PACK,       (u32)GetItemID::GI_MAGIC_BEAN,          ITEMTYPE_ITEM );
    itemTable[DOUBLE_DEFENSE]                    = Item(true,      false,          &noVariable,                  Text{"Double Defense",                  "Double défence",                                   "Doble poder defensivo"},                              DOUBLE_DEFENSE,         0xB2,                                  ITEMTYPE_GFAIRY );
	itemTable[OCARINA_OF_TIME]                   = Item(true,      false,          &Ocarina,                     Text{"Ocarina of Time",                 "Ocarina du temps",                                 "Ocarina del Tiempo"},                                 OCARINA_OF_TIME,       (u32)GetItemID::GI_OCARINA_OF_TIME,     ITEMTYPE_ITEM );
    itemTable[PICTOGRAPH_BOX]                    = Item(true,      false,          &Pictobox,                    Text{"Pictograph Box",                  "Boite a Images",                                   "Camara Pictografica"},                                PICTOGRAPH_BOX,        (u32)GetItemID::GI_PICTOGRAPH_BOX,      ITEMTYPE_ITEM );
    itemTable[POWDER_KEG]                        = Item(true,      true,           &PowderKeg,                   Text{"Powder Keg",                      "Baril de Poudre",                                  "Barril de Polovora"},                                 POWDER_KEG,            (u32)GetItemID::GI_POWDER_KEG,          ITEMTYPE_ITEM );
    itemTable[KEATON_MASK]                       = Item(true,      false,          &KeatonMask,                  Text{"Keaton Mask",                     "Masque de Keaton",                                 "Careta de Keaton"},                                   KEATON_MASK,           (u32)GetItemID::GI_MASK_KEATON,         ITEMTYPE_MASK );
    itemTable[BUNNY_HOOD]                        = Item(true,      false,          &BunnyHood,                   Text{"Bunny Hood",                      "Masque du lapin",                                  "Capucha de conejo"},                                  BUNNY_HOOD,            (u32)GetItemID::GI_MASK_BUNNY_HOOD,     ITEMTYPE_MASK );
    itemTable[GORON_MASK]                        = Item(true,      false,          &GoronMask,                   Text{"Goron Mask",                      "Masque Goron",                                     "Máscara Goron"},                                      GORON_MASK,            (u32)GetItemID::GI_MASK_GORON,          ITEMTYPE_MASK );
    itemTable[ZORA_MASK]                         = Item(true,      false,          &ZoraMask,                    Text{"Zora Mask",                       "Masque Zora",                                      "Máscara Zora"},                                       ZORA_MASK,             (u32)GetItemID::GI_MASK_ZORA,           ITEMTYPE_MASK );
    itemTable[DEKU_MASK]                         = Item(true,      false,          &DekuMask,                    Text{"Deku Mask",                       "Masque Mojo",                                      "Máscara Deku"},                                       DEKU_MASK,             (u32)GetItemID::GI_MASK_DEKU,           ITEMTYPE_MASK );
    itemTable[POSTMANS_HAT]                      = Item(true,      false,          &PostmansHat,                 Text{"Postman's Hat",                   "Chapeau de facteur",                               "Sombrero de cartero"},                                POSTMANS_HAT,          (u32)GetItemID::GI_MASK_POSTMANS,       ITEMTYPE_MASK );
    itemTable[ALL_NIGHT_MASK]                    = Item(true,      false,          &AllNightMask,                Text{"All-Night Mask",                  "Masque de nuit",                                   "Máscara toda la noche"},                              ALL_NIGHT_MASK,        (u32)GetItemID::GI_MASK_ALL_NIGHT,      ITEMTYPE_MASK );
    itemTable[BLAST_MASK]                        = Item(true,      false,          &BlastMask,                   Text{"Blast Mask",                      "Masque anti-explosion",                            "Máscara explosiva"},                                  BLAST_MASK,            (u32)GetItemID::GI_MASK_BLAST,          ITEMTYPE_MASK );
    itemTable[STONE_MASK]                        = Item(true,      false,          &StoneMask,                   Text{"Stone Mask",                      "Masque de pierre",                                 "Máscara de piedra"},                                  STONE_MASK,            (u32)GetItemID::GI_MASK_STONE,          ITEMTYPE_MASK );
    itemTable[GREAT_FAIRYS_MASK]                 = Item(true,      false,          &GreatFairyMask,              Text{"Great Fairy's Mask",              "Masque de grande fee",                             "Máscara de gran hada"},                               GREAT_FAIRYS_MASK,     (u32)GetItemID::GI_MASK_GREAT_FAIRYS,   ITEMTYPE_MASK );
    itemTable[BREMEN_MASK]                       = Item(true,      false,          &BremenMask,                  Text{"Bremen Mask",                     "Masque de Breme",                                  "Máscara de Bremen"},                                  BREMEN_MASK,           (u32)GetItemID::GI_MASK_BREMEN,         ITEMTYPE_MASK );
    itemTable[DON_GEROS_MASK]                    = Item(true,      false,          &DonGerosMask,                Text{"Don Gero's Mask",                 "Masque de Don Gero",                               "Máscara de Don Gero"},                                DON_GEROS_MASK,        (u32)GetItemID::GI_MASK_DON_GEROS,      ITEMTYPE_MASK );
    itemTable[MASK_OF_SCENTS]                    = Item(true,      false,          &MaskOfScents,                Text{"Mask of Scents",                  "Masque des Senteurs",                              "Máscara de aromas"},                                  MASK_OF_SCENTS,        (u32)GetItemID::GI_MASK_OF_SCENTS,      ITEMTYPE_MASK );
    itemTable[ROMANIS_MASK]                      = Item(true,      false,          &RomanisMask,                 Text{"Romani's Mask",                   "Masque de Romani",                                 "Máscara de Romani"},                                  ROMANIS_MASK,          (u32)GetItemID::GI_MASK_ROMANIS,        ITEMTYPE_MASK );
    itemTable[CIRCUS_LEADERS_MASK]               = Item(true,      false,          &CircusLeadersMask,           Text{"Troupe Leader's Mask",            "Masque de chef de troupe",                         "Máscara de lider de troupe"},                         CIRCUS_LEADERS_MASK,   (u32)GetItemID::GI_MASK_TROUPE_LEADERS, ITEMTYPE_MASK );
    itemTable[KAFEIS_MASK]                       = Item(true,      false,          &KafeisMask,                  Text{"Kafei's Mask",                    "Masque de Kafei",                                  "Máscara de Kafei"},                                   KAFEIS_MASK,           (u32)GetItemID::GI_MASK_KAFEIS,         ITEMTYPE_MASK );
    itemTable[COUPLES_MASK]                      = Item(true,      false,          &CouplesMask,                 Text{"Couple's Mask",                   "Masque de couple",                                 "Máscara de pareja"},                                  COUPLES_MASK,          (u32)GetItemID::GI_MASK_COUPLES,        ITEMTYPE_MASK );
    itemTable[KAMAROS_MASK]                      = Item(true,      false,          &KamarosMask,                 Text{"Kamaro's Mask",                   "Masque de Kamaro",                                 "Máscara de Kamaro"},                                  KAMAROS_MASK,          (u32)GetItemID::GI_MASK_KAMARAOS,       ITEMTYPE_MASK );
    itemTable[GIBDOS_MASK]                       = Item(true,      false,          &GibdosMask,                  Text{"Gibdo Mask",                      "Masque Gibdo",                                     "Máscara de Gibdo"},                                   GIBDOS_MASK,           (u32)GetItemID::GI_MASK_GIBDO,          ITEMTYPE_MASK );
    itemTable[GAROS_MASK]                        = Item(true,      false,          &GarosMask,                   Text{"Garo's Mask",                     "Masque de Garo",                                   "Máscara de Garo"},                                    GAROS_MASK,            (u32)GetItemID::GI_MASK_GARO,           ITEMTYPE_MASK );
    itemTable[CAPTAINS_HAT]                      = Item(true,      false,          &CaptainsHat,                 Text{"Captain's Hat",                   "Chapeau de capitaine",                             "Sombrero de Capitan"},                                CAPTAINS_HAT,          (u32)GetItemID::GI_MASK_CAPTAINS_HAT,   ITEMTYPE_MASK );
    itemTable[GIANTS_MASK]                       = Item(true,      false,          &GiantsMask,                  Text{"Giant's Mask",                    "Masque de geant",                                  "Máscara de gigante"},                                 GIANTS_MASK,           (u32)GetItemID::GI_MASK_GIANTS,         ITEMTYPE_MASK );
    itemTable[FIERCE_DIETY_MASK]                 = Item(true,      false,          &FierceDietyMask,             Text{"Fierce Diety Mask",               "Masque Dietetique Fiere",                          "Máscara Fiere Diety"},                                FIERCE_DIETY_MASK,     (u32)GetItemID::GI_MASK_FIERCE_DEITY,   ITEMTYPE_MASK );
    itemTable[MASK_OF_TRUTH]                     = Item(true,      false,          &MaskOfTruth,                 Text{"Mask of Truth",                   "Masque de vérité",                                 "Máscara de la Verdad"},                               MASK_OF_TRUTH,         (u32)GetItemID::GI_MASK_OF_TRUTH,       ITEMTYPE_MASK );
    itemTable[FISHING_PASS]                      = Item(false,     true,           &noVariable,                  Text{"Fishing Pass",                    "Fishing Pass",                                     "Fishing Pass"},                                       FISHING_PASS,          0xBA,                                   ITEMTYPE_ITEM );
//
    //Swamp Spider Tokens
    itemTable[SWAMP_SKULLTULA_TOKEN]             = Item(true,      true,           &SwampSkulltulaTokens,        Text{"Swamp Skulltula Token",           "Jeton de Skulltula dorée",                         "Símbolo de skulltula dorada" },                       SWAMP_SKULLTULA_TOKEN, (u32)GetItemID::GI_GOLD_SKULLTULA_SPIRIT, ITEMTYPE_TOKEN);

    //Oceanside Spider Tokens
    itemTable[OCEANSIDE_SKULLTULA_TOKEN]         = Item(true,      true,           &OceanSkulltulaTokens,        Text{"Oceanside Skulltula Token",       "Jeton de Skulltula dorée",                         "Símbolo de skulltula dorada" },                       OCEANSIDE_SKULLTULA_TOKEN, (u32)GetItemID::GI_GOLD_SKULLTULA_SPIRIT, ITEMTYPE_TOKEN);
    
    //Stray Fairies//

    //Clock Town Fairies
	itemTable[CT_STRAY_FAIRY]					 = Item(true,      true,           &ClockTownStrayFairy,         Text{"Clock Town Stray Fairy",		   "Fee errante de la Bourg-Clocher",	               "Cuidad Reloj Hada Callejera"},                        CT_STRAY_FAIRY,  (u32)GetItemID::GI_NONE,  ITEMTYPE_STRAYFAIRY);
	
    //Woodfall Stray Fairies
    itemTable[WF_STRAY_FAIRY]                    = Item(true,      true,           &WoodfallStrayFairies,        Text{"Woodfall Stray Fairy",		   "Fee errante de la Bois-Cascade",	               "Hada Callejera del Bosque  Catarata" },               WF_STRAY_FAIRY,  (u32)GetItemID::GI_NONE,  ITEMTYPE_STRAYFAIRY);
    
    //Snowhead Stray Fairies
    itemTable[SH_STRAY_FAIRY]                    = Item(true,      true,           &SnowheadStrayFairies,        Text{"Snowhead Stray Fairy",		   "Fee errante de la Pic des Neiges",	               "Hada Callejera del Pico Nevado" },                    SH_STRAY_FAIRY,  (u32)GetItemID::GI_NONE,  ITEMTYPE_STRAYFAIRY);
    
    //Great Bay Stray Fairies
    itemTable[GBT_STRAY_FAIRY]                   = Item(true,      true,           &GreatBayStrayFairies,        Text{"Great Bay Stray Fairy",		   "Fee errante de la Grande Baie",	                   "Gran Hada Callejera de la Bahia" },                   GBT_STRAY_FAIRY, (u32)GetItemID::GI_NONE,  ITEMTYPE_STRAYFAIRY);
    
    //Stone Tower Stray Fairies 
    itemTable[ST_STRAY_FAIRY]                    = Item(true,      true,           &StoneTowerStrayFairies,     Text{"Stone Tower Stray Fairy",       "Fee errante de la Forteresse de Pierre",           "Hada Callejera de la Torre Piedra" },                 ST_STRAY_FAIRY,  (u32)GetItemID::GI_NONE,  ITEMTYPE_STRAYFAIRY);
    
    //Bottles 
    itemTable[EMPTY_BOTTLE1]                     = Item(true,      false,          &DampeBottle,                 Text{"Empty Bottle",                    "Flacon vide",                                      "Botella vacía" },                                   EMPTY_BOTTLE1,                (u32)GetItemID::GI_BOTTLE_EMPTY,              ITEMTYPE_ITEM);
    itemTable[EMPTY_BOTTLE2]                     = Item(true,      false,          &BeaverRaceBottle,            Text{"Empty Bottle",                    "Flacon vide",                                      "Botella vacía" },                                   EMPTY_BOTTLE2,                (u32)GetItemID::GI_BOTTLE_EMPTY,              ITEMTYPE_ITEM);
    itemTable[EMPTY_BOTTLE]                      = Item(true,      false,          &HasBottle,                   Text{"Empty Bottle",                    "Flacon vide",                                      "Botella vacía" },                                   EMPTY_BOTTLE,                 (u32)GetItemID::GI_BOTTLE_EMPTY,              ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_MILK]                  = Item(true,      false,          &AlienBottle,                 Text{"Bottle with Milk",                "Flacon de lait",                                   "Botella de leche Lon Lon"},                         BOTTLE_WITH_MILK,             (u32)GetItemID::GI_BOTTLE_MILK,               ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_RED_POTION]            = Item(true,      false,          &WitchBottle,                 Text{"Bottle with Red Potion",          "Flacon de potion rouge",                           "Botella de poción roja"},                           BOTTLE_WITH_RED_POTION,       (u32)GetItemID::GI_BOTTLE_POTION_RED,         ITEMTYPE_ITEM);
    itemTable[GOLD_DUST]                         = Item(true,      true,           &GoronRaceBottle,             Text{"Gold Dust",   			  	     "Poudre d'Or",       	      		                 "Polvo de Oro" },                                    GOLD_DUST,                    (u32)GetItemID::GI_BOTTLE_GOLD_DUST,          ITEMTYPE_QUEST);
    itemTable[CHATEAU_ROMANI]                    = Item(true,      false,          &ChateauBottle,               Text{"Chateau Romani",           	     "Chateau Romani",          	                     "Reserva Romani" },                                  CHATEAU_ROMANI,               (u32)GetItemID::GI_BOTTLE_CHATEAU_ROMANI,     ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_MYSTERY_MILK]          = Item(true,      true,           &MysteryMilkBottle,           Text{"Bottle with Mystery Milk",        "Bottle with Mystery Milk",                         "Bottle with Mystery Milk"},                         BOTTLE_WITH_MYSTERY_MILK,     (u32)GetItemID::GI_BOTTLE_MYSTERY_MILK,       ITEMTYPE_QUEST);
    //Other bottle items
    itemTable[DEKU_PRINCESS]                     = Item(true,      true,           &DekuPrincess,                Text{"Deku Princess",   			     "Princesse Mojo",       	                         "Princesa Deku"},                                    DEKU_PRINCESS,                (u32)GetItemID::GI_DEKU_PRINCESS_FAIRY,       ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_GREEN_POTION]          = Item(false,     false,          &HasBottle,                   Text{"Bottle with Green Potion",        "Flacon de potion verde",                           "Botella de poción verte"},                          BOTTLE_WITH_GREEN_POTION,     (u32)GetItemID::GI_POTION_GREEN,              ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_BLUE_POTION]           = Item(false,     false,          &HasBottle,                   Text{"Bottle with Blue Potion",         "Flacon de potion azul",                            "Botella de poción bleu"},                           BOTTLE_WITH_BLUE_POTION,      (u32)GetItemID::GI_POTION_BLUE,               ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_FAIRY]                 = Item(false,     true,           &HasBottle,                   Text{"Bottle with Fairy",               "Bottle with Fairy",                                "Bottle with Fairy",},                               BOTTLE_WITH_FAIRY,            (u32)GetItemID::GI_FAIRY,                     ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_BUGS]                  = Item(false,     true,           &HasBottle,                   Text{"Bottle with Bugs",                "Bottle with Bugs",                                 "Bottle with Bugs",},                                BOTTLE_WITH_BUGS,             (u32)GetItemID::GI_BOTTLE_BUG,                ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_FISH]                  = Item(false,     true,           &HasBottle,                   Text{"Bottle with Fish",                "Bottle with Fish",                                 "Bottle with Fish"},                                 BOTTLE_WITH_FISH,             (u32)GetItemID::GI_BOTTLE_FISH,               ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_POE]                   = Item(false,     true,           &HasBottle,                   Text{"Bottle with Poe",                 "Bottle with Poe",                                  "Bottle with Poe",},                                 BOTTLE_WITH_POE,              (u32)GetItemID::GI_BOTTLE_POE_TEXT,           ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_BIG_POE]               = Item(false,     true,           &HasBottle,                   Text{"Bottle with Big Poe",             "Bottle with Big Poe",                              "Bottle with Big Poe",},                             BOTTLE_WITH_BIG_POE,          (u32)GetItemID::GI_BOTTLE_BIG_POE,            ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_SPRING_WATER]          = Item(false,     true,           &HasBottle,                   Text{"Bottle with Spring Water",        "Bottle with Spring Water",                         "Bottle with Spring Water",},                        BOTTLE_WITH_SPRING_WATER,     (u32)GetItemID::GI_BOTTLE_SPRING_WATER,       ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_HOT_SPRING_WATER]      = Item(false,     true,           &HasBottle,                   Text{"Bottle with Hot Spring Water",    "Bottle with Hot Spring Water",                     "Bottle with Hot Spring Water",},                    BOTTLE_WITH_HOT_SPRING_WATER, (u32)GetItemID::GI_BOTTLE_HOT_SPRING_WATER,   ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_ZORA_EGG]              = Item(false,     true,           &HasBottle,                   Text{"Bottle with Zora Egg",            "Bottle with Zora Egg",                             "Bottle with Zora Egg",},                            BOTTLE_WITH_ZORA_EGG,         (u32)GetItemID::GI_BOTTLE_ZORA_EGG,           ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_MUSHROOM]              = Item(false,     true,           &HasBottle,                   Text{"Bottle with Mushroom",            "Bottle with Mushroom",                             "Bottle with Mushroom",},                            BOTTLE_WITH_MUSHROOM,         (u32)GetItemID::GI_BOTTLE_MAGIC_MUSHROOM,     ITEMTYPE_ITEM);
    itemTable[ZORA_EGG]							 = Item(false,     true,           &ZoraEgg,                     Text{"Zora Egg", 					     "Oeuf de Zora",						             "Huevo de Zora"},							          ZORA_EGG,			    	    (u32)GetItemID::GI_BOTTLE_ZORA_EGG,           ITEMTYPE_ITEM);
	itemTable[SEAHORSE]							 = Item(true,     true,           &Seahorse,                    Text{"Seahorse",						 "Hippocampe",						                 "Caballo de mar"},							          SEAHORSE,				        (u32)GetItemID::GI_BOTTLE_SEAHORSE,           ITEMTYPE_ITEM);
	
    //Upgrades
    itemTable[RAZOR_SWORD]                       = Item(true,      false,          &RazorSword,                  Text{"Razor Sword",				       "Lame Rasoir",					                   "Espada Afilada" },                                RAZOR_SWORD,          (u32)GetItemID::GI_RAZOR_SWORD,     ITEMTYPE_ITEM );
    itemTable[GILDED_SWORD]                      = Item(true,      false,          &GildedSword,                 Text{"Gilded Sword",                    "Lame Doree",                                       "Espada de Esmeril" },                               GILDED_SWORD,         (u32)GetItemID::GI_GILDED_SWORD,    ITEMTYPE_ITEM );
    itemTable[MIRROR_SHIELD]                     = Item(true,      false,          &MirrorShield,                Text{"Mirror Shield",                   "Bouclier miroir",                                  "Escudo espejo" },                                   MIRROR_SHIELD,        (u32)GetItemID::GI_SHIELD_MIRROR,   ITEMTYPE_ITEM );
    itemTable[LARGE_QUIVER]                      = Item(true,      false,          &TownArcheryQuiver,           Text{"Large Quiver",                    "Large Quiver",                                     "Large Quiver", },                                   LARGE_QUIVER,         (u32)GetItemID::GI_LARGE_QUIVER,    ITEMTYPE_ITEM);
    itemTable[LARGEST_QUIVER]                    = Item(true,      false,          &SwampArcheryQuiver,          Text{"Largest Quiver",                  "Largest Quiver",                                   "Largest Quiver," },                                 LARGEST_QUIVER,       (u32)GetItemID::GI_LARGEST_QUIVER,  ITEMTYPE_ITEM );
    itemTable[BOMB_BAG]                          = Item(true,      false,          &BombBag20,                   Text{"Bomb Bag",                        "Bomb Bag",                                         "Bomb Bag" },                                        BOMB_BAG,             (u32)GetItemID::GI_BOMB_BAG_20,     ITEMTYPE_ITEM);
    itemTable[BIG_BOMB_BAG]                      = Item(true,      false,          &TownBombBag,                 Text{"Big Bomb Bag",                    "Big Bomb Bag",                                     "Big Bomb Bag" },                                    BIG_BOMB_BAG,         (u32)GetItemID::GI_BOMB_BAG_30,     ITEMTYPE_ITEM);
    itemTable[BIGGEST_BOMB_BAG]                  = Item(true,      false,          &MountainBombBag,             Text{"Biggest Bomb Bag",                "Biggest Bomb Bag",                                 "Biggest Bomb Bag" },                                BIGGEST_BOMB_BAG,     (u32)GetItemID::GI_BOMB_BAG_40,     ITEMTYPE_ITEM);
    itemTable[ADULT_WALLET]                      = Item(true,      false,          &Townwallet200,               Text{"Adult Wallet",                    "Adult Wallet",                                     "Adult Wallet" },                                    ADULT_WALLET,         (u32)GetItemID::GI_ADULT_WALLET,    ITEMTYPE_ITEM);
    itemTable[GIANT_WALLET]                      = Item(true,      false,          &OceanWallet500,              Text{"Giant Wallet",                    "Giant Wallet",                                     "Giant Wallet" },                                    GIANT_WALLET,         (u32)GetItemID::GI_GIANT_WALLET,    ITEMTYPE_ITEM);
    itemTable[MAGIC_POWER]                       = Item(true,      false,          &MagicPower,                  Text{"Magic Power",                     "Magic Power",                                      "Magic Power",},                                     MAGIC_POWER,          (u32)GetItemID::GI_NONE,            ITEMTYPE_ITEM);
    itemTable[EXTENDED_MAGIC_POWER]              = Item(true,      false,          &ExtendedMagicPower,          Text{"Extended Magic Power",            "Extended Magic Power",                             "Extended Magic Power",},                            EXTENDED_MAGIC_POWER, (u32)GetItemID::GI_NONE,            ITEMTYPE_ITEM);

    //Songs
    //itemTable[SONG_OF_TIME]                      = Item(Text{"Song of Time",                    "Chant du temps",                   "Canción del tiempo"},                      ITEMTYPE_SONG,     0xC5,              true,        &SongOfTime,             SONG_OF_TIME,				false,);
    itemTable[SONG_OF_STORMS]                    = Item(true,      false,          &SongOfStorms,                Text{"Song of Storms",                  "Chant des tempêtes",                               "Canción de la tormenta"},                           SONG_OF_STORMS,        (u32)GetItemID::GI_NONE, ITEMTYPE_SONG);
    itemTable[SONATA_OF_AWAKENING]               = Item(true,      false,          &SonataOfAwakening,           Text{"Sonata of Awakening",             "Sonate de i'Eveil",                                "Sonata del Despertar"},                             SONATA_OF_AWAKENING,   (u32)GetItemID::GI_NONE, ITEMTYPE_SONG );
    itemTable[LULLABY_INTRO]                     = Item(true,      false,          &LullabyIntro,                Text{"Goron's Lullaby Intro",           "Goron's Lullaby Intro",                             "Goron's Lullaby Intro"},                           LULLABY_INTRO,         (u32)GetItemID::GI_NONE, ITEMTYPE_SONG );
    itemTable[GORONS_LULLABY]                    = Item(true,      false,          &GoronsLullaby,               Text{"Goron's Lullaby",                 "Berceuse des Gorons",                              "Nana Goron"},                       		          GORONS_LULLABY,        (u32)GetItemID::GI_NONE, ITEMTYPE_SONG);
    itemTable[NEW_WAVE_BOSSA_NOVA]               = Item(true,      false,          &NewWaveBossaNova,            Text{"New Wave Bossa Nova",             "Bossa Nova des Flots",                             "Nueva Bossanova"},                                  NEW_WAVE_BOSSA_NOVA,   (u32)GetItemID::GI_NONE, ITEMTYPE_SONG );
    itemTable[ELEGY_OF_EMPTINESS]                = Item(true,      false,          &ElegyOfEmptiness,            Text{"Elegy of Emptiness",              "Hymne du Vida",                                    "Elegia al Vacio"},                                  ELEGY_OF_EMPTINESS,    (u32)GetItemID::GI_NONE, ITEMTYPE_SONG );
    itemTable[OATH_TO_ORDER]               		 = Item(true,      false,          &OathToOrder,                 Text{"Oath to Order",             	   "Ode lAppel",       		                           "Oda al Order"},   			                          OATH_TO_ORDER,         (u32)GetItemID::GI_NONE, ITEMTYPE_SONG );
    itemTable[EPONAS_SONG]                       = Item(true,      false,          &EponasSong,                  Text{"Epona's Song",                    "Chant d'Épona",                                    "Canción de Epona"},                                 EPONAS_SONG,           (u32)GetItemID::GI_NONE, ITEMTYPE_SONG );
    //itemTable[INVERTED_SONG_OF_TIME]             = Item(true,0,                       0,                  Text{"Inverted Song of Time",           "Chant du Temps Inverse",           "Canción del Tiempo Invertida"},            ITEMTYPE_SONG,     0xC2,              true,        &InvertedSongOfTime,     INVERTED_SONG_OF_TIME,		false,);
    //itemTable[SONG_OF_DOUBLE_TIME]               = Item(true,0,                       0,                  Text{"Song of Double Time",             "Chant du Temps Accelere",          "Canción del Doble Tiempo"},                ITEMTYPE_SONG,     0xC3,              true,        &SongOfDoubleTime,       SONG_OF_DOUBLE_TIME,		false,);
    itemTable[SONG_OF_HEALING]                   = Item(true,      false,          &SongOfHealing,               Text{"Song of Healing",                 "Chant de l'Apaisement",                            "Sonata de Curacion"},                               SONG_OF_HEALING,       (u32)GetItemID::GI_NONE, ITEMTYPE_SONG );
    itemTable[SONG_OF_SOARING]                   = Item(true,      false,          &SongOfSoaring,               Text{"Song of Soaring",                 "Chant de l'Envol",                                 "Canción de Vuelo"},                                 SONG_OF_SOARING,       (u32)GetItemID::GI_NONE, ITEMTYPE_SONG );
    
    //Maps and Compasses
    itemTable[WOODFALL_TEMPLE_MAP]               = Item(false,     false,          &noVariable,                  Text{"Woodfall Temple Map",             "Carte de Temple de Bois-Cascade",                  "Mapa del Templo del Bosque Catarata"},              WOODFALL_TEMPLE_MAP,        (u32)0xAE,                 ITEMTYPE_MAP );
    itemTable[SNOWHEAD_TEMPLE_MAP]               = Item(false,     false,          &noVariable,                  Text{"Snowhead Temple Map",             "Carte de Temple du Pic des Neiges",                "Mapa del Templo del Pico Nevado"},                  SNOWHEAD_TEMPLE_MAP,        (u32)0xAF,                 ITEMTYPE_MAP );
    itemTable[GBT_MAP]                           = Item(false,     false,          &noVariable,                  Text{"Great Bay Temple Map",            "Carte de Temple de la Grande Baie",                "Mapa del Templo de la Gran Bahia"},                 GBT_MAP,                    (u32)0xB0,                 ITEMTYPE_MAP );
    itemTable[STONE_TOWER_TEMPLE_MAP]            = Item(false,     false,          &noVariable,                  Text{"Stone Tower Temple Map",          "Carte du Temple de la Forteresse de Pierre",       "Mapa del Templo de la Torre de Piedra"},            STONE_TOWER_TEMPLE_MAP,     (u32)0xB1,                 ITEMTYPE_MAP);
    itemTable[CLOCK_TOWN_MAP]                    = Item(false,     false,          &noVariable,                  Text{"Clock Town Map",                  "Carte de Bourg-Clocher",                           "Mapa de la Cuidad Reloj"},                          CLOCK_TOWN_MAP,             (u32)GetItemID::GI_MAP_OF_CLOCK_TOWN,   ITEMTYPE_MAP);
    itemTable[WOODFALL_MAP]                      = Item(false,     false,          &noVariable,                  Text{"Woodfall Map",                    "Carte du Bois-Cascade",                            "Mapa del Bosque Catarata"},                         WOODFALL_MAP,               (u32)GetItemID::GI_MAP_OF_WOODFALL,     ITEMTYPE_MAP);
    itemTable[SNOWHEAD_MAP]                      = Item(false,     false,          &noVariable,                  Text{"Snowhead Map",                    "Carte du Pic Des Neiges",                          "Mapa del Pico Nevado"},                             SNOWHEAD_MAP,               (u32)GetItemID::GI_MAP_OF_SNOWHEAD,     ITEMTYPE_MAP);
    itemTable[GREAT_BAY_MAP]                     = Item(false,     false,          &noVariable,                  Text{"Great Bay Map",                   "Carte du Plage de la Grande Baie",                 "Mapa del Costa de la Gran Bahia"},                  GREAT_BAY_MAP,              (u32)GetItemID::GI_MAP_OF_GREAT_BAY,    ITEMTYPE_MAP);
    itemTable[STONE_TOWER_MAP]                   = Item(false,     false,          &noVariable,                  Text{"Stone Tower Map",                 "Carte du Forteresse de Pierre",                    "Mapa del Torre de Piedra"},                         STONE_TOWER_MAP,            (u32)GetItemID::GI_MAP_OF_STONE_TOWER,  ITEMTYPE_MAP);
    itemTable[ROMANI_RANCH_MAP]                  = Item(false,     false,          &noVariable,                  Text{"Romani Ranch Map",                "Carte de Ranch Romani",                            "Mapa de Rancho Romani"},                            ROMANI_RANCH_MAP,           (u32)GetItemID::GI_MAP_OF_ROMANI_RANCH, ITEMTYPE_MAP);

    itemTable[WOODFALL_TEMPLE_COMPASS]           = Item(false,     false,          &noVariable,                  Text{"Woodfall Temple Compass",         "Boussole de Temple de Bois-Cascade",               "Brújula del Templo del Bosque Catarata"},           WOODFALL_TEMPLE_COMPASS,    (u32)0xA7, ITEMTYPE_COMPASS );
    itemTable[SNOWHEAD_TEMPLE_COMPASS]           = Item(false,     false,          &noVariable,                  Text{"Snowhead Temple Compass",         "Boussole de Temple du Pic des Neiges",             "Brújula del Templo del Pico Nevado"},               SNOWHEAD_TEMPLE_COMPASS,    (u32)0xA8, ITEMTYPE_COMPASS );
    itemTable[GBT_COMPASS]                       = Item(false,     false,          &noVariable,                  Text{"Great Bay Temple Compass",        "Boussole de Temple de la Grande Baie",             "Brújula del Templo de la Gran Bahia"},              GBT_COMPASS,                (u32)0xAC, ITEMTYPE_COMPASS );
    itemTable[STONE_TOWER_TEMPLE_COMPASS]        = Item(false,     false,          &noVariable,                  Text{"Stone Tower Temple Compass",      "Boussole du Teple de la Forteresse de Pierre",     "Brújula del Templo de la Torre de Piedra"},         STONE_TOWER_TEMPLE_COMPASS, (u32)0xAD, ITEMTYPE_COMPASS );

    //Boss Keys
    itemTable[WOODFALL_TEMPLE_BOSS_KEY]          = Item(true,      false,           &BossKeyWoodfallTemple,       Text{"Woodfall Temple Big Key",         "Clé d'or du Temple de Bois-Cascade",               "Gran llave del Templo del Bosque Catarata"},        WOODFALL_TEMPLE_BOSS_KEY,    (u32)0xA3, ITEMTYPE_BOSSKEY );
    itemTable[SNOWHEAD_TEMPLE_BOSS_KEY]          = Item(true,      false,           &BossKeySnowheadTemple,       Text{"Snowhead Temple Big Key",         "Clé d'or du Temple du Pic des Neiges",             "Gran llave del Templo del Pico Nevado"},            SNOWHEAD_TEMPLE_BOSS_KEY,    (u32)0xA4, ITEMTYPE_BOSSKEY );
    itemTable[GBT_BOSS_KEY]                      = Item(true,      false,           &BossKeyGreatBayTemple,       Text{"Great Bay Temple Big Key",        "Clé d'or du Temple de la Grande Baie",             "Gran llave del Templo de la Gran Bahia"},           GBT_BOSS_KEY,                (u32)0xA5, ITEMTYPE_BOSSKEY );
    itemTable[STONE_TOWER_TEMPLE_BOSS_KEY]       = Item(true,      false,           &BossKeyStoneTowerTemple,     Text{"Stone Tower Temple Big Key",      "Clé d'or du Temple de la Forteresse de Pierre",    "Gran llave del Templo de la Torre de Piedra"},      STONE_TOWER_TEMPLE_BOSS_KEY, (u32)0xA6, ITEMTYPE_BOSSKEY );
    //Small Keys
    itemTable[WOODFALL_TEMPLE_SMALL_KEY]         = Item(true,      false,           &WoodfallTempleKeys,          Text{"Woodfall Temple Small Key",       "Petite clé du Temple de Bois-Cascade",             "Llave del Templo del Templo del Bosque Catarata"},  WOODFALL_TEMPLE_SMALL_KEY,    (u32)0x76, ITEMTYPE_SMALLKEY );
    itemTable[SNOWHEAD_TEMPLE_SMALL_KEY]         = Item(true,      false,           &SnowheadTempleKeys,          Text{ "Snowhead Temple Small Key",      "Petite clé du Temple du Pic des Neiges",           "Llave del Templo del Pico Nevado" },                SNOWHEAD_TEMPLE_SMALL_KEY,    (u32)0x77, ITEMTYPE_SMALLKEY);
    itemTable[GBT_SMALL_KEY]                     = Item(true,      false,           &GreatBayTempleKeys,          Text{"Great Bay Temple Small Key",      "Petite clé du Temple de la Grande Baie",           "Llave del Templo del la Gran Bahia"},               GBT_SMALL_KEY,                (u32)0x90, ITEMTYPE_SMALLKEY );
    itemTable[STONE_TOWER_TEMPLE_SMALL_KEY]      = Item(true,      false,           &StoneTowerTempleKeys,        Text{ "Stone Tower Temple Small Key",   "Petite clé du Temple de la Forteresse de Pierre",  "Llave del Templo de la Torre de Piedra" },          STONE_TOWER_TEMPLE_SMALL_KEY, (u32)0xA2, ITEMTYPE_SMALLKEY);
   
    //Boss Remains
    itemTable[ODOLWAS_REMAINS]                   = Item(true,      false,          &OdolwaRemains,               Text{"Odolwa's Remains",                "Restes d'Odolwa",                                  "Restos de Odolwa"},                                 ODOLWAS_REMAINS,    (u32)GetItemID::GI_ODOLWAS_REMAINS,   ITEMTYPE_DUNGEONREWARD );
    itemTable[GOHTS_REMAINS]                     = Item(true,      false,          &GohtRemains,                 Text{"Goht's Remains",                  "Restes de Rohrk",                                  "Restos de Goht"},                                   GOHTS_REMAINS,      (u32)GetItemID::GI_GOHTS_REMAINS,     ITEMTYPE_DUNGEONREWARD);
    itemTable[GYORGS_REMAINS]                    = Item(true,      false,          &GyorgRemains,                Text{"Gyorg's Remains",                 "Restes de Gyorg",                                  "Restos de Gyorg"},                                  GYORGS_REMAINS,     (u32)GetItemID::GI_GYORGS_REMAINS,    ITEMTYPE_DUNGEONREWARD );
    itemTable[TWINMOLDS_REMAINS]                 = Item(true,      false,          &TwinmoldRemains,             Text{"Twinmold's Remains",              "Restes de Skorn",                                  "Restos dde Twinmod"},                               TWINMOLDS_REMAINS,  (u32)GetItemID::GI_TWINMOLDS_REMAINS, ITEMTYPE_DUNGEONREWARD );
    
    //Pre Clock Town??
    //itemTable[PRE_CLOCK_TOWN_CHEST]              = Item(false,0,                      &noVariable,                  Text{ "Deku Nuts (10)",                  "Noix Mojo (10)",                   "Nueces deku (10)" },                                     "Pre-Clock Town Chest",                        Region::BeneathClockTown,        PRE_CLOCK_TOWN_CHEST,              (u32)GetItemID::GI_NUTS_10, ItemCategory::DekuNuts,      LocationCategory::GlitchesRequired);

    //Generic Items
    itemTable[RECOVERY_HEART]                    = Item(false,     true,           &noVariable,                  Text{"Recovery Heart",                  "Cœur d'énergie",                                   "Corazón"},                                          RECOVERY_HEART,                    (u32)GetItemID::GI_RECOVERY_HEART_SINGLE,  ITEMTYPE_ITEM);
    itemTable[GREEN_RUPEE]                       = Item(false,     true,           &noVariable,                  Text{"Green Rupee",                     "Rubis vert",                                       "Rupia verde"},                                      GREEN_RUPEE,                       (u32)GetItemID::GI_RUPEE_GREEN,  ITEMTYPE_ITEM);
    itemTable[BLUE_RUPEE]                        = Item(false,     true,           &noVariable,                  Text{"Blue Rupee",                      "Rubis bleu",                                       "Rupia azul"},                                       BLUE_RUPEE,                        (u32)GetItemID::GI_RUPEE_BLUE,  ITEMTYPE_ITEM);
    itemTable[RED_RUPEE]                         = Item(false,     true,           &noVariable,                  Text{"Red Rupee",                       "Rubis rouge",                                      "Rupia roja"},                                       RED_RUPEE,                         (u32)GetItemID::GI_RUPEE_RED,  ITEMTYPE_ITEM);
    itemTable[PURPLE_RUPEE]                      = Item(false,     true,           &noVariable,                  Text{"Purple Rupee",                    "Rubis pourpre",                                    "Rupia morada"},                                     PURPLE_RUPEE,                      (u32)GetItemID::GI_RUPEE_PURPLE,  ITEMTYPE_ITEM);
    itemTable[HUGE_RUPEE]                        = Item(false,     true,           &noVariable,                  Text{"Huge Rupee",                      "Énorme rubis",                                     "Rupia gigante"},                                    HUGE_RUPEE,                        (u32)GetItemID::GI_RUPEE_GOLD,  ITEMTYPE_ITEM);
    itemTable[SILVER_RUPEE]                      = Item(false,     true,           &noVariable,                  Text{"Silver Rupee",                    "rubis d'argent",                                   "Rupia de plata"},                                   SILVER_RUPEE,                      (u32)GetItemID::GI_RUPEE_SILVER, ITEMTYPE_ITEM);
    itemTable[PIECE_OF_HEART]                    = Item(false,     false,          &PiecesOfHeart,               Text{"Piece of Heart",                  "Quart de cœur",                                    "Pieza de corazón"},                                 PIECE_OF_HEART,                    (u32)GetItemID::GI_HEART_PIECE,  ITEMTYPE_ITEM);
    itemTable[HEART_CONTAINER]                   = Item(false,     false,          &HeartContainers,             Text{"Heart Container",                 "Réceptacle de cœur",                               "Contenedor de corazón"},                            HEART_CONTAINER,                   (u32)GetItemID::GI_HEART_CONTAINER,  ITEMTYPE_ITEM);
    itemTable[ICE_TRAP]                          = Item(false,     true,           &noVariable,                  Text{"Ice Trap",                        "Piège de glace",                                   "Trampa de hielo"},                                  ICE_TRAP,                          0x12,  ITEMTYPE_ITEM);
    itemTable[MILK]                              = Item(false,     true,           &HasBottle,                   Text{"Milk",                            "Lait",                                             "Leche Lon Lon"},                                    NONE,                              0x92,                          ITEMTYPE_ITEM);

    //Refills
    itemTable[BOMBS_5]                           = Item(false,     true,           &noVariable,                  Text{"Bombs (5)",                       "Bombes (5)",                                       "Bombas (5)" },                                      BOMBS_5,                           (u32)GetItemID::GI_BOMBS_5, ITEMTYPE_REFILL);
    itemTable[BOMBS_10]                          = Item(false,     true,           &noVariable,                  Text{"Bombs (10)",                      "Bombes (10)",                                      "Bombas (10)" },                                     BOMBS_10,                          (u32)GetItemID::GI_BOMBS_10, ITEMTYPE_REFILL);
    itemTable[BOMBS_20]                          = Item(false,     true,           &noVariable,                  Text{"Bombs (20)",                      "Bombes (20)",                                      "Bombas (20)" },                                     BOMBS_20,                          (u32)GetItemID::GI_BOMBS_20, ITEMTYPE_REFILL);
    itemTable[BOMBCHU_5]                         = Item(false,     true,           &noVariable,                  Text{"Bombchu (5)",                     "Bombchus (5)",                                     "Bombchus (5)" },                                    BOMBCHU_5,                         (u32)GetItemID::GI_BOMBCHUS_5, ITEMTYPE_REFILL);
    itemTable[BOMBCHU_10]                        = Item(false,     true,           &noVariable,                  Text{"Bombchu (10)",                    "Bombchus (10)",                                    "Bombchus (10)" },                                   BOMBCHU_10,                        (u32)GetItemID::GI_BOMBCHUS_10, ITEMTYPE_REFILL);
    itemTable[BOMBCHU_20]                        = Item(false,     true,           &noVariable,                  Text{"Bombchu (20)",                    "Bombchus (20)",                                    "Bombchus (20)" },                                   BOMBCHU_20,                        (u32)GetItemID::GI_BOMBCHU_20, ITEMTYPE_REFILL);
    //itemTable[BOMBCHU_DROP] = Item(Text{ "Bombchu Drop",                    "Bombchus",                         "Bombchus" }, ITEMTYPE_DROP, GI_BOMBCHUS_10, true, &BombchuDrop, NONE, true, );
    itemTable[ARROWS_10]                         = Item(false,     true,           &noVariable,                  Text{"Arrows (10)",                     "Flèches (10)",                                     "Flechas (10)" },                                    ARROWS_10,                         0x1E, ITEMTYPE_REFILL);
    itemTable[ARROWS_30]                         = Item(false,     true,           &noVariable,                  Text{"Arrows (30)",                     "Flèches (30)",                                     "Flechas (30)" },                                    ARROWS_30,                         0x1F,  ITEMTYPE_REFILL);
    itemTable[ARROWS_40]                         = Item(false,     true,           &noVariable,                  Text{"Arrows (40)",                     "Flèches (40)",                                     "Flechas (40)" },                                    ARROWS_40,                         0x20,  ITEMTYPE_REFILL);
    itemTable[ARROWS_50]                         = Item(false,     true,           &noVariable,                  Text{"Arrows (50)",                     "Flèches (50)",                                     "Flechas (50)" },                                    ARROWS_50,                         0x21,  ITEMTYPE_REFILL);
    itemTable[DEKU_NUTS_5]                       = Item(false,     true,           &noVariable,                  Text{"Deku Nuts (5)",                   "Noix Mojo (5)",                                    "Nueces deku (5)" },                                 DEKU_NUTS_5,                       (u32)GetItemID::GI_NUTS_5,        ITEMTYPE_REFILL);
    itemTable[DEKU_NUTS_10]                      = Item(false,     true,           &noVariable,                  Text{"Deku Nuts (10)",                  "Noix Mojo (10)",                                   "Nueces deku (10)" },                                DEKU_NUTS_10,                      (u32)GetItemID::GI_NUTS_10,       ITEMTYPE_REFILL);
    itemTable[DEKU_STICK_1]                      = Item(false,     true,           &noVariable,                  Text{"Deku Stick (1)",                  "Bâton Mojo (1)",                                   "Palo deku (1)" },                                   DEKU_STICK_1,                      (u32)GetItemID::GI_STICKS_1,      ITEMTYPE_REFILL);
    itemTable[RED_POTION_REFILL]                 = Item(false,     true,           &noVariable,                  Text{"Red Potion Refill",               "Potion rouge",                                     "Recarga de poción roja" },                          RED_POTION_REFILL,                 (u32)GetItemID::GI_POTION_RED,    ITEMTYPE_REFILL);
    itemTable[GREEN_POTION_REFILL]               = Item(false,     true,           &noVariable,                  Text{"Green Potion Refill",             "Potion verte",                                     "Recarga de poción verde" },                         GREEN_POTION_REFILL,               (u32)GetItemID::GI_POTION_GREEN,  ITEMTYPE_REFILL);
    itemTable[BLUE_POTION_REFILL]                = Item(false,     true,           &noVariable,                  Text{"Blue Potion Refill",              "Potion bleue",                                     "Recarga de poción azul" },                          BLUE_POTION_REFILL,                (u32)GetItemID::GI_POTION_BLUE,   ITEMTYPE_REFILL);
    //Shop Items                                              Repeatable				price
    itemTable[BUY_ARROWS_10]                     = Item(false,     true,           &noVariable,                  Text{"Buy Arrows (10)",                 "Acheter: Flèches (10)",                            "Comprar flechas (10)"},                             BUY_ARROWS_10,       (u32)GetItemID::GI_ARROWS_MEDIUM, ITEMTYPE_SHOP);  
    itemTable[BUY_ARROWS_30]                     = Item(false,     true,           &noVariable,                  Text{"Buy Arrows (30)",                 "Acheter: Flèches (30)",                            "Comprar flechas (30)"},                             BUY_ARROWS_30,	   (u32)GetItemID::GI_ARROWS_LARGE,  ITEMTYPE_SHOP);
    itemTable[BUY_DEKU_NUT_10]                   = Item(false,     true,           &noVariable,                  Text{"Buy Deku Nut (10)",               "Acheter: Noix Mojo (10)",                          "Comprar Nueces deku (10)"},                         BUY_DEKU_NUT_10,	   (u32)GetItemID::GI_NUTS_10,       ITEMTYPE_SHOP);
    itemTable[BUY_DEKU_STICK_1]                  = Item(false,     true,           &noVariable,                  Text{"Buy Deku Stick (1)",              "Acheter: Bâton Mojo (1)",                          "Comprar palos deku (1)"},                           BUY_DEKU_STICK_1,	   (u32)GetItemID::GI_STICKS_1,      ITEMTYPE_SHOP);
    itemTable[BUY_BOMBS_10]                      = Item(false,     true,           &noVariable,                  Text{"Buy Bombs (10)",                  "Acheter: Bombes (10)",                             "Comprar Bombas (10)"},                              BUY_BOMBS_10,	       (u32)GetItemID::GI_BOMBS_10,      ITEMTYPE_SHOP);
    itemTable[BUY_RED_POTION]                    = Item(false,     true,           &noVariable,                  Text{"Buy Red Potion ",                 "Acheter: Potion rouge ",                           "Comprar poción roja "},                             BUY_RED_POTION,	   (u32)GetItemID::GI_POTION_RED,    ITEMTYPE_SHOP);
    itemTable[BUY_GREEN_POTION]                  = Item(false,     true,           &noVariable,                  Text{"Buy Green Potion",                "Acheter: Potion verte",                            "Comprar poción verde"},                             BUY_GREEN_POTION,    (u32)GetItemID::GI_POTION_GREEN,  ITEMTYPE_SHOP);
    itemTable[BUY_BLUE_POTION]                   = Item(false,     true,           &noVariable,                  Text{"Buy Blue Potion",                 "Acheter: Potion bleue",                            "Comprar poción azul"},                              BUY_BLUE_POTION,	   (u32)GetItemID::GI_POTION_BLUE,   ITEMTYPE_SHOP);
    itemTable[BUY_HEROS_SHIELD]                  = Item(false,     true,           &noVariable,                  Text{"Buy Hero's Shield",               "Acheter: Bouclier Hylien",                         "Comprar escudo hyliano"},                           BUY_HEROS_SHIELD,	   (u32)GetItemID::GI_SHIELD_HERO,   ITEMTYPE_SHOP);
    itemTable[BUY_BOMBCHU_10]                    = Item(false,     true,           &noVariable,                  Text{"Buy Bombchu (10)",                "Acheter: Bombchus (10)",                           "Comprar bombchus (10)"},                            BUY_BOMBCHU_10,	   (u32)GetItemID::GI_BOMBCHUS_10,   ITEMTYPE_SHOP);
    itemTable[SOLD_OUT]                          = Item(false,     true,           &noVariable,                  Text{"Sold Out",                        "Vendu",                                            "Vendido"},                                          SOLD_OUT,	           (u32)GetItemID::GI_NONE,          ITEMTYPE_SHOP);
    itemTable[BUY_FAIRYS_SPIRIT]                 = Item(false,     true,           &noVariable,                  Text{"Buy Fairy's Spirit",              "Acheter: Fée",                                     "Comprar hada"},                                     BUY_FAIRYS_SPIRIT,   (u32)GetItemID::GI_FAIRY,         ITEMTYPE_SHOP);
    itemTable[BUY_MAGIC_BEAN]                    = Item(false,     true,           &noVariable,                  Text{"Buy Magic Bean",                  "Buy Magic Bean",                                   "Buy Magic Bean"},                                   BUY_MAGIC_BEAN,      (u32)GetItemID::GI_MAGIC_BEAN,    ITEMTYPE_SHOP);
    //Progressive Items
    itemTable[PROGRESSIVE_SWORD]                 = Item(true,     false,          &ProgressiveSword,            Text{"Progressive Sword",			   "Lame (prog.)",					                    "Espada progresivo" },                                PROGRESSIVE_SWORD,       0x4A,                           ITEMTYPE_ITEM);
    itemTable[PROGRESSIVE_BOMB_BAG]              = Item(true,     false,          &ProgressiveBombBag,          Text{"Progressive Bomb Bag",            "Sac de bombes (prog.)",                           "Saco de bombas progresivo" },                        PROGRESSIVE_BOMB_BAG,    0x46,                           ITEMTYPE_ITEM);
    itemTable[PROGRESSIVE_BOW]                   = Item(true,     false,          &ProgressiveBow,              Text{"Progressive Bow",                 "Arc (prog.)",                                     "Arco progresivo" },                                  PROGRESSIVE_BOW,         0x47,                           ITEMTYPE_ITEM);
    itemTable[PROGRESSIVE_WALLET]                = Item(true,     false,          &ProgressiveWallet,           Text{"Progressive Wallet",              "Bourse (prog.)",                                  "Bolsa de rupias progresiva" },                       PROGRESSIVE_WALLET,      0x48,                           ITEMTYPE_ITEM);
    itemTable[PROGRESSIVE_MAGIC_METER]           = Item(true,     false,          &ProgressiveMagic,            Text{"Progressive Magic Meter",         "Jauge de magie (prog.)",                          "Poder mágico progresivo" },                          PROGRESSIVE_MAGIC_METER, 0x49,                           ITEMTYPE_GFAIRY);

    itemTable[MAJORAS_MASK]                      = Item(true,      false,          &noVariable,                  Text{"Majora's Mask",                   "Majora's Mask",                                    "Majora's Mask" },                                   MAJORAS_MASK,                      (u32)GetItemID::GI_ERROR_NOTHING_40,   ITEMTYPE_EVENT);
    itemTable[HINT]                              = Item(true,      true,           &noVariable,                  Text{"Hint",                            "Indice",                                           "Pista" },                                           HINT,                              (u32)GetItemID::GI_ERROR_NOTHING_40,   ITEMTYPE_EVENT);
    
  //itemTable[PROGRESSIVE_BOMBCHUS] = Item(Text{ "Progressive Bombchu",             "Bombchus (prog.)",                 "Bombchus progresivos" }, ITEMTYPE_ITEM, 0x89, true, &Bombchus, PROGRESSIVE_BOMBCHUS, false, );
  //  itemTable[PROGRESSIVE_NUT_UPGRADE]           = Item(Text{"Progressive Nut Capacity",        "Capacité de noix (prog.)",         "Capacidad de nueces deku progresiva"},     ITEMTYPE_ITEM,     0x87,              false,      &noVariable,             PROGRESSIVE_NUT_UPGRADE,     false,);
  //  itemTable[PROGRESSIVE_STICK_UPGRADE]         = Item(Text{"Progressive Stick Capacity",      "Capacité de bâtons (prog.)",       "Capacidad de palos deku progresiva"},      ITEMTYPE_ITEM,     0x88,              false,       &noVariable,            PROGRESSIVE_STICK_UPGRADE,   false,);
  

};

Item& ItemTable(const ItemKey itemKey) {
    return itemTable[itemKey];
};

//This function should only be used to place items containing hint text
//at gossip stone locations
void NewItem(const ItemKey itemKey, const Item item) {
    if (itemKey <= PROGRESSIVE_MAGIC_METER) {
        printf("\x1b[25;0HWARNING: ATTEMPTED TO OVERWRITE ITEM %lu\n", itemKey);
        return;
    }
    itemTable[itemKey] = item;
}